### ISSUE TITLE
Using Farady's raise_error middleware causes circuits to never open

### ISSUE THREAD

**Issue by philsturgeon** [yammer/circuitbox#101]
I have a repeatable issue, where circuits will remain closed on multiple failures when using the Faraday middleware. 

```
require 'faraday'
require 'circuitbox/faraday_middleware'
require 'webmock'
include WebMock::API

WebMock.enable!

stub_request(:any, "http://example.com")
  .to_return(status: 500, body: lambda { |request| sleep rand(0...2); 'abc' })

  conn = Faraday.new(:url => "http://example.com") do |c|
    c.use Circuitbox::FaradayMiddleware, circuit_breaker_options: {
      logger: Logger.new(STDOUT),
    }
    c.response :raise_error # <-- The offender is right here, removing it works just fine
    c.adapter :net_http
  end

  60.times.each do |i|
    begin
      puts "\n==============\nRequest #{i}"
      response = conn.get("/")
    rescue StandardError => err
      puts "Error (#{err.class}): #{err.message}"
    else
      puts "Success: status=#{response.status}"
    end
  end
```

Just to show, the last few lines:

```
==============
Request 57
D, [2018-06-01T15:58:53.788828 #39] DEBUG -- : [CIRCUIT] closed: querying example.com
Error (Faraday::ClientError): the server responded with status 500

==============
Request 58
D, [2018-06-01T15:58:54.792850 #39] DEBUG -- : [CIRCUIT] closed: querying example.com
Error (Faraday::ClientError): the server responded with status 500

==============
Request 59
D, [2018-06-01T15:58:54.794794 #39] DEBUG -- : [CIRCUIT] closed: querying example.com
Error (Faraday::ClientError): the server responded with status 500
```

I guess the exception is causing the circuitbreaker logic to be skipped. I'm going to dig into this now as we need it at work, but if you have any tips on how to write a failing test for your test suite that'd be great.

**Comment by sideshowcoder** [comment]
`raise_error` is implemented as a FaradayMiddleware if I remember right so I guess the error is due to ordering of the middlewares, looking at 

https://github.com/yammer/circuitbox/blob/master/lib/circuitbox/faraday_middleware.rb#L42

it looks like when the you have the inner (aka later installed) middleware raising an error this error might not be wrapped in a circuitbox error and therefor bypassing the logic of the Circuitbox middleware and not being counted. Sorry I can't verify that right now but it would be my hunch to check if the order of the middlewares changes the behavior.

I might be wrong on this but maybe worth a starting point.

**Comment by philsturgeon** [comment]
Ha, yeah @sideshowcoder you're spot on. I had circuitbox _then_ raise, which I thought would work out fine. I just swapped em so that it's raise then circuitbox, and that seems to have worked!

I've pretty much finished #102 which will make the order irrelevant. Should I continue with this, or should we just add a note somewhere prominent saying (register raise_error **before** circuitbox if you want it to actually work)?

My concern right now is that if we don't do #102, a bunch of people will just ignore it, and circuitbox will not do the ultimate excellence it's meant to be doing.

**Comment by sideshowcoder** [comment]
Personally I like to make the order irrelevant as it is a an error which is easy to make and hard to debug so I'm all for making the change in #102

**Comment by philsturgeon** [comment]
I abandoned #102 for now, as a) I was having trouble getting it to work properly, and b) _vacaaaaation!_. 

If you'd like to pick this up, I would really appreciate it. If I made the mistake somebody else will.

**Comment by sideshowcoder** [comment]
Enjoy the time off :) and thanks for spending the time to debug this!
