### ISSUE TITLE
Need a New Release version with changes including removing of timeouts 

### ISSUE THREAD

**Issue by karthyfd** [yammer/circuitbox#114]
I could see that 1.1.1 is the latest release version available. We want to incorporate the changes that recently went (https://github.com/yammer/circuitbox/pull/106/files). We could rely on master as there can be any breakages as well.  So could you please create a new tag and publish it in ruby gems, so that we can use the latest stable release version.

**Comment by matthewshafer** [comment]
We'll have a release soon, probably a prerelease while I work on documentation and upgrade information.

Some of the breaking changes from 1.x are the removal of partitions, circuit options changed from attr_writer to attr_reader, removal of ruby timeout (which was already mentioned).
