### ISSUE TITLE
2.0.0 Release

### ISSUE THREAD

**Issue by davidrees** [yammer/circuitbox#137]
Is there anything I can help work on to wrap up 2.0.0?

**Comment by matthewshafer** [comment]
Yes! One of the changes I have yet to start is unifying the simple and monotonic timers (lib/circuitbox/timer/*) into a single timer that uses the monotonic clock on the system where that is available, if not falls back to something like simple timer.

There's a ton of documentation work to get done in regards to upgrading from 1.x to 2.x, public method documentation, and the readme (I have some local changes to the readme that I should commit).

Lower priority things

- The functional tests can randomly fail due to how they open ports, I'd like to change them.
- Clean up the excon middleware (similar to the cleanup for the faraday middleware).


There are other in-progress things I've been working on when I have time (which seems to be very little these days 😢)

**Comment by silasb** [comment]
Any updates on this?  Seems like there is a healthy amount of commits going into `main`.   By chance is Yammer using this 2.0.0.pre4 on production?

**Comment by matthewshafer** [comment]
> Any updates on this? Seems like there is a healthy amount of commits going into `main`. 

Nope. I do have a bunch of documentation work to do first. Hopefully nothing crazy comes up. No joke every time I've been ready to release 2.0.0 I've spotted some issue. For example issues when circuit states change (hopefully it's better now).

> By chance is Yammer using this 2.0.0.pre4 on production?

Nope. I'll reach out to one of the other teams and see if they are interested in upgrading.

**Comment by coding-bunny** [comment]
any progress on this, as we'd love to be able to upgrade to Faraday `~> 1.0` but circuitbox is the blocker in this.

**Comment by jayrapson** [comment]
@matthewshafer any updates on this? Would love to use this in an upcoming project but the official 1.1.x releases aren't compatible with Ruby 3. 

Is there a list of known/open issues which are blocking the 2.0 release?

**Comment by JeffMorhous** [comment]
@matthewshafer Is there anything I can do to help get 2.0.0 over the finish line?

**Comment by matthewshafer** [comment]
At the moment the remaining work looks like this

* Merge my one open PR
* Investigate/finish work with time window performance when using the built in in-memory circuit store
* Check test coverage
  * Add tests if needed
* Write a 1.x to 2.x upgrade guide
* Improve documentation
  * How to use circuitbox
    * standalone
    * faraday
  * What to watch out for
    * edge cases with dynamic config
    * differences when not using the in memory storage
    * faraday parallel adapters (not supported)

**Comment by djberg96** [comment]
@matthewshafer If you add a FUNDING.yml file, I might (stress *might*) be able to get my company to make a donation to help along a 2.0 release. :)

**Comment by matthewshafer** [comment]
@djberg96 What would be helpful would be feedback on how the latest circuitbox changes work in a testing environment. We've put the recent changes though quite a bit of use and its been working well for us but outside testing would be great. If it would be useful for me to release an another prerelease let me know.

**Comment by ritikesh** [comment]
@matthewshafer we've been using circuitbox(with redis) in production on the main branch extensively for sometime now and haven't had any troubles so far. Things do look stable and should be good for a release. IMO, things like documentation, deeper test cases, etc can be added in follow-up releases

**Comment by matthewshafer** [comment]
Here is the timeline I'm thinking for 2.0.0. This may change for a few reasons: 1. Virtually all the work I do on circuitbox is outside of my normal work schedule, sometimes I need a break. 2. For reasons I can't share my work schedule has been pretty intense lately, I've had less time then I anticipated I would have.

I have a few changes I've been working one and my hope is to have PR's for them by Wednesday (3/29). Once they are merged I'll release 2.0.0.pre5. Once that's on rubygems I'll switch a service I work on to that version and monitor the changes across various environments for 1-2 weeks. During that time I can continue work on documentation in circuitbox for upgrading, updates to the readme, and potential things to watch out for. If I don't find any issues and there aren't any reported here, I'll release 2.0.0.

**Comment by matthewshafer** [comment]
I pushed circuitbox 2.0.0.pre5 to rubygems this evening. Please try it out if you have time and let me know how it goes. Over the next 1-2 weeks I'll continue improving / writing documentation for circuitbox while we test this version in some of our services. The action I have to build the gem and create a release needs some updates so I may release a pre6 during the 1-2 weeks, just to make sure the action is updated, but the higher priority for me is documentation.

**Comment by matthewshafer** [comment]
2.0.0 is released
