### ISSUE TITLE
Clarify what :your_service is

### ISSUE THREAD

**Issue by PLMspitts** [yammer/circuitbox#147]
https://github.com/yammer/circuitbox#usage
Is `:your_service` in the readme, also used with `:yammer`, just something to identify the service you're using the circuit breaker on? Or is it supposed to be something specific? It should be clarified in the README.

**Comment by PLMspitts** [comment]
I think I get it now; it's how you identify one "circuit", so you use one name for each circuit that can open, and they're treated as the same circuit. That should be added to the documentation

**Comment by matthewshafer** [comment]
To answer your question, ```:your_service``` is just an identifier for the circuit you want to create or use (when ```Circuitbox.circuit``` is called). If you call ```Circuitbox.circuit(:your_service)``` multiple times you would be given the same circuit. If you call ```Circuitbox.circuit(:other_service)``` you'd get back a different circuit that doesn't share the same state (open, half_open, closed) as the ```:your_service``` circuit. Let us know if you have any other questions.

Going forward I'm going to be removing most of the code examples from the readme and add code documentation.

**Comment by PLMspitts** [comment]
Great! Then I'm all set, if documentation is going to be added :+1:
