### ISSUE TITLE
Is possible to open/close the circuit manually?

### ISSUE THREAD

**Issue by juliofalbo** [yammer/circuitbox#152]
I would like to implement the circuitbox but I need to have the ability to handle this manually, I mean, open/close manually.

And if yes, I also would like to know if can I use another strategy (like a SQL DB) to control the state of the circuit.

**Comment by matthewshafer** [comment]
There aren't any plans to expose a public api to open/close a circuit manually. This could start to move Circuitbox into the realm of turning a feature on/off which would be better suited by other libraries. As far as storing the circuit state in a SQL database, it's possible if Moneta supports that but that would significantly increase the circuit latency and add additional failure cases.

**Comment by ramontayag** [comment]
In my case, I want to avoid using exceptions for control flow, and instead open the circuit if the http status code is `429`, for example.

I'm still reading through issues and documentation to see if there's a way to do it with `open_circuit`.

**Comment by matthewshafer** [comment]
@ramontayag If you are using the faraday middleware setting the `open_circuit` lambda should let you decide what status code(s) would be considered failed requests.

**Comment by ramontayag** [comment]
I'm considering moving to Faraday for this. thanks @matthewshafer
