### ISSUE TITLE
Use single state variable

### ISSUE THREAD

**Issue by sideshowcoder** [yammer/circuitbox#21]
Have one circuit per machine.

**Comment by yarmand** [comment]
We need a shared place in memory for atomic increment/decrement of rates.

**Comment by sideshowcoder** [comment]
We probably want to enable the use of shared memory to save that. Maybe using https://github.com/pmahoney/process_shared or we can go with creating a small CExtentions, as I'm not sure we want to use FFI for this.

The basic Idea is that we pass a name of a shared memory section http://menehune.opt.wfu.edu/Kokua/More_SGI/007-2478-008/sgi_html/ch03.html and open it on every process to save the state. This means we are backing the counters mentioned by shared memory. This also needs a cross process Mutex.

**Comment by sideshowcoder** [comment]
another Idea from the hacknight was to publish a notification of a nopen circuit to some system, which we could then react on on other machines or the same machine.

**Comment by sideshowcoder** [comment]
Out of a conversation with Avdi Grimm came the idea to make it pluggable via Moneta which supports an awefull lot of stores https://github.com/minad/moneta

**Comment by sideshowcoder** [comment]
This has been implemented and merged.
