### ISSUE TITLE
Faraday Middleware creating two requests

### ISSUE THREAD

**Issue by chiefcll** [yammer/circuitbox#28]
faraday_middleware.rb line 32
```
def call(request_env)
      service_response = nil
      check_circuit_open!(request_env)
      circuit(request_env).run!(run_options(request_env)) do
        @app.call(request_env).on_complete do |env|
          service_response = Faraday::Response.new(env)
          raise RequestFailed if open_circuit?(service_response)
        end
      end
```

The check circuit runs the request which causes a successful request to be made and logged. Every request that fails first gets logged as successful and then as failed. Its doubling the number of requests. This affects the volume_threshold and stats. Looks like line 32 can just be deleted.

**Comment by sideshowcoder** [comment]
Thanks for the Issue and the PRs I'll take a look at this when I'm back on tuesday, just wanted to let you know :+1:

**Comment by chiefcll** [comment]
Great - I just cleaned up my patch... Added some tests to show what the problem was. Looks like the volume_threshold was doubled because it was making twice as many requests - So I cleaned that up a bit.
