### ISSUE TITLE
Circuit is not opened after passing volume_threshold (no notification)

### ISSUE THREAD

**Issue by chiefcll** [yammer/circuitbox#31]
If you have a volume_threshold of 5, and you have 6 failing requests - open? returns true - however the event is not logged because open! is not called until the 7th request.

I'll work on a patch for this.

**Comment by sideshowcoder** [comment]
That seems indeed wrong, but as I'm a little fuzzy on the logic here @yarmand do you mind taking a look at this? This could either be a mistake in `open?` or in the logic to call `open!` thats why I feel more context might be helpful, either way the docs shoud be clearer on this I would say.

**Comment by matthewshafer** [comment]
I believe I fixed this in #116, from quite some time ago and never closed out the issue. Circuitbox doesn't require a circuit to run an additional time and opening is calculated when a circuit fails, rather than when `open?` is called. This should lead to more predictable circuit states.
