### ISSUE TITLE
Faraday middleware circuit breaker is catching all errors

### ISSUE THREAD

**Issue by chiefcll** [yammer/circuitbox#33]
Currently, Circuitbox is catching all errors instead of catching just open circuit errors.
Line 38 Faraday_middleware should be changed to:
```
    rescue Circuitbox::OpenCircuitError
```

I expect the service should raise a Timeout Error etc when an actual call is made. The null / default response should only be returned when a call wasn't made due to the circuit being open.

**Comment by nickcampbell18** [comment]
I assume you're referring to [this line](https://github.com/yammer/circuitbox/blob/31da04ca805bd39b23d86cc6b57665a863520caa/lib/circuitbox/faraday_middleware.rb#L39)?

It should only catch two types of error:
* `OpenCircuitError`
* `ServiceFailureError`

Both of these are emitted by the Circuitbox library to declare either the service being unavailable, or receiving an unexpected response, but in both case it wraps the original exception before continuing down the middleware stack. You should be able to do this to recapture your exception:

```ruby
rescue Circuitbox::Error => e
  e.original_exception
```

**Comment by chiefcll** [comment]
Yes. 

A ServiceFailureError is any non 200 response. The service made an actual request and got back a response (which I'd prefer to be returned) - that gets captured there and changed to a 503 with a default response. I'd prefer that you only get the default 503 error when a network request was never made because the circuit was open, rather than always getting that response on a non 200 response from an actual network call. HTTP has many error codes which are used by applications.

**Comment by sideshowcoder** [comment]
I see now what you meant there. The default behaviour is checking the response for success, but this behaviour is configurable by passing a block via the open_circuit option to the middleware. This block will get called to determine if the response should be regarded a failure that would count towards opening a circuit or not. Faraday itself only throws an exception for things like timeout by default, 500, 400, don't cause an exception  but sucess will be false on the response which trips the default open_circuit handler. 
Does that work for you?

**Comment by chiefcll** [comment]
My bug was from version 10.0 - where it wasn't adding the error information. With 10.3 the changes should work fine. I'll close this out.

**Comment by sideshowcoder** [comment]
Perfect thanks :)
