### ISSUE TITLE
Circuit trips on 4xx errors

### ISSUE THREAD

**Issue by nickcampbell18** [yammer/circuitbox#45]
Currently, we use the `Faraday::Response` method `#success?` to establish [if a request should trip the circuit](https://github.com/yammer/circuitbox/blob/3c270b8cb5393b7b80b9fe29752a8f0c1d1d5f0c/lib/circuitbox/faraday_middleware.rb#L26).

However, a circuit breaker should probably only trip when the destination is unable to handle the request, i.e. a 5xx server error. A 4xx error probably implies that the user made a bad request.

I propose we change this line to something like this:

```diff
diff --git a/lib/circuitbox/faraday_middleware.rb b/lib/circuitbox/faraday_middleware.rb
index 1b79a6f..a260530 100644
--- a/lib/circuitbox/faraday_middleware.rb
+++ b/lib/circuitbox/faraday_middleware.rb
@@ -23,7 +23,7 @@ class Circuitbox

     def initialize(app, opts = {})
       @app = app
-      default_options = { open_circuit: lambda { |response| !response.success? } }
+      default_options = { open_circuit: lambda { |response| (500..599).cover?(response.status) } }
       @opts = default_options.merge(opts)
       super(app)
     end
```

If there is a more idiomatic way of determining "server failure", I think that would be great too. Also, do we need to cover `response.status == 0`, for when the host wasn't responsive?

**Comment by nickcampbell18** [comment]
@sideshowcoder If you need some help updating the readme or adding some information about this decision, let me know.

**Comment by sideshowcoder** [comment]
@nickcampbell18 `0` should raise an exception in faraday so we are good here, as we catch this. Otherwise yes that should definatly be redefined, as we are close to `1.0` I think this is the time to change this.

**Comment by yarmand** [comment]
I agree, 4xx overwhelming should be handled by the rate limiting mechanism server side.
