### ISSUE TITLE
Broken expires with new Moneta store

### ISSUE THREAD

**Issue by sebastian-julius** [yammer/circuitbox#51]
With the latest 1.0.1 version of Circuitbox the circuits **don't close** again after an error!

In our Redis tests the asleep entry hadn't had a TTL but was endless (-1).

**Comment by sebastian-julius** [comment]
@sideshowcoder have you had a chance to look into this?

**Comment by sideshowcoder** [comment]
Sorry just saw this, I'm taking a look now. Sorry for taking so long!
