### ISSUE TITLE
Using Moneta for Redis, circuitbreaker redis keys don't expire

### ISSUE THREAD

**Issue by guyisra** [yammer/circuitbox#64]
I use Moneta with

```
circuit_breaker_options: {
                     error_threshold:  ERROR_THRESHOLD_PERCENT,
                     volume_threshold: VOLUME_THRESHOLD,
                     sleep_window:     SLEEP_WINDOW,
                     time_window:      TIME_WINDOW,
                     cache:            Moneta.new(:Redis, backend: Redis.new)
                   },
```

in a faraday middleware configuration

But I see that circuit breaker creates keys in redis that don't expire. 

The key looks like 

`circuits:ServiceName::stats:1486909800:success`

I know that #52 might have solved that, but for me at least it didn't.
Should I manually set the expiry somewhere, or am I missing a configuration?

**Comment by olegykz** [comment]
I have bumped into the same issue and it turned out that the reason is in the `Moneta` gem (at least versions 1.0.0 - 1.4.0) - their documentation tells about `expires: true` option while it accepts the only integer values (like `expires: 24.days.to_i`) - otherwise keys would have indefinite TTL
