### ISSUE TITLE
New release of circuitbreaker

### ISSUE THREAD

**Issue by shs96c** [yammer/circuitbox#79]
It's been almost a year since the last release of circuitbreaker, and since then a reasonable number of changes have been merged. Could you please release a new version of the gem?

**Comment by yarmand** [comment]
You are absolutely right @shs96c , thank you for reminding us.
@matthewshafer There is a few changes that are more than fixes in the changelog, should we go for V1.2.0 ?

**Comment by matthewshafer** [comment]
@yarmand It would be v2.0.0 since there are some breaking changes currently in the master branch. There are a few other minor things to get done first (like testing under 2.5) before we should make a release. I might have some time this weekend to do that.

**Comment by alsutton** [comment]
Is there any update on the release? We're currently using a fork with the PR merged in so it'd be nice to return to the source of truth.

**Comment by matthewshafer** [comment]
I've still been working on quite a few changes. A few were merged last week and there's a few in progress. Some of these have changed the api a bit and some I'm working on will too. So far it hasn't been anything too drastic, mostly things that don't have much documentation already.

I'm not sure if putting some of the todos for releases on github would help, if it does let me know and I can look into that.

**Comment by matthewshafer** [comment]
It's probably good for a pre-release gem after I can get some colleagues to review my open pr's. These change Circuitbox quite a bit, #118 #119.

**Comment by matthewshafer** [comment]
2.0.0.pre1 has been released to rubygems so I'm going to close out this issue.

I may make additional changes to circuitbox before 2.0.0.

**Comment by alsutton** [comment]
Is there an ETA for a stable release? I don't think I'd be able to get the justification for the engineering effort needed to deploy a pre-release version which is still subject to change before a going full 2.0.

**Comment by davidrees** [comment]
Can 2.0.0 be released? It would be great to have the fixes to the half-open logic.
